#!/bin/sh

. /usr/lib/ushi/libushi

case "$1" in
    start)
        log "Mounting all local filesystems..."; {
            mount -a || exit 1
        }

        log "Enabling swap..."; {
            swapon -a || exit 1
        }
    ;;
    stop)
        log "Unmounting filesystems and disabling swap..."; {
        swapoff -a

        # Skip unmounting pseudo filesystems as they may be
        # needed below for encryption and user shutdown scripts.
        #
        # The '-t' flag is a part of the LSB standard and is
        # supported by busybox, toybox, util-linux, FreeBSD,
        # NetBSD, OpenBSD and others.
        #
        # This flag is unsupported by ubase and I consider this
        # a ubase issue. ubase only supports Linux and this
        # flag is a part of the Linux standard base.
        umount -rat nosysfs,noproc,nodevtmpfs,notmpfs
    }

    log "Remounting rootfs as read-only"; {
        mount -o remount,ro /
        sync
    }
    ;;
esac
