#!/bin/sh

. /usr/lib/ushi/libushi

case "$1" in
    start)
        log "Setting hostname..."; {
            read -r hostname < /etc/hostname
            printf %s "${hostname:-(none)}" > /proc/sys/kernel/hostname
        } 2>/dev/null
    ;;
    stop)
    ;;
esac
