#!/bin/sh
[ $$ -eq 1 ] || exit 1
. /usr/lib/ushi/libushi

# 1: runlevel
# 2: command
run_level() {
    level="$1"
    cmd="$2"
    for file in "/usr/lib/ushi/runlevels/$level"/*; do
        [ -x "$file" ] && {
            log "Starting service ${file##*/}"
            "$file" "$1" || { 
                log "FAILED"
                [ "$level" = boot ] && sos
            }
        }
    done
}

boot() {
    run_level sysinit start
    run_level boot start
}

_reboot() {
    run_level boot stop
    run_level powerdown start
    run_level reboot start
}

_poweroff() {
    run_level boot stop
    run_level powerdown start
    run_level poweroff start
}

boot

trap _poweroff USR1
trap _reboot INT

while :; do
    sleep 86400
done
